
stages:
  - ci
  - cleanup
  - cd

variables:
  PYTHON_VERSION: "3.11"
  IMAGE_BASE: python:${PYTHON_VERSION}-slim-bullseye

.run_ci:
  stage: ci
  image: ${IMAGE_BASE}
  interruptible: true
  script:
    - cd $CI_PROJECT_DIR/$DATA_PROJECT_DIR

    # Create Python Virtual Environment
    - python -m venv .venv
    - source .venv/bin/activate

    # Install Tinybird CLI
    - pip install tinybird-cli

    # Tinybird version
    - tb --version

    # Check all the data files syntax
    - tb check

    # Create new test Environment with data
    - |
      tb \
        --host $TB_HOST \
        --token $ADMIN_TOKEN \
        env create tmp_ci_${CI_COMMIT_SHORT_SHA} \
        --last-partition --wait

    # List changes with production Workspace
    - tb diff --production --no-verbose

    # Push changes to the test Environment
    - |
      PUSH_FILE=./deployment/${CI_COMMIT_REF_NAME}-push.sh
      if [ -f "$PUSH_FILE" ]; then
        ./deployment/${CI_COMMIT_REF_NAME}-push.sh
      else
        tb push --push-deps --only-changes --force --populate --wait
      fi

    # List changes with test Environment (should be empty)
    - tb diff

    # Run data quality tests
    - tb test run -v

    # Run pipe regression tests
    - |
      echo ${CI_MERGE_REQUEST_LABELS}
      tb env regression-tests coverage --wait $(echo ${CI_MERGE_REQUEST_LABELS} | tr , ' ')


.cleanup_ci_branch:
  stage: cleanup
  image: ${IMAGE_BASE}
  script:
    - cd $CI_PROJECT_DIR/$DATA_PROJECT_DIR

    # Create Python Virtual Environment
    - python -m venv .venv
    - source .venv/bin/activate

    # Install Tinybird CLI
    - pip install tinybird-cli

    # Tinybird version
    - tb --version

    # Remove test Environment
    - |
      tb \
      --host $TB_HOST \
      --token $ADMIN_TOKEN \
      env rm tmp_ci_${CI_COMMIT_SHORT_SHA} \
      --yes

.run_cd:
  stage: cd
  image: ${IMAGE_BASE}
  interruptible: true
  script:
    - cd $CI_PROJECT_DIR/$DATA_PROJECT_DIR

    # Create Python Virtual Environment
    - python -m venv .venv
    - source .venv/bin/activate

    # Install Tinybird CLI
    - pip install tinybird-cli

    # Tinybird version
    - tb --version

    # Check all the data files syntax
    - tb check

    # Auth in the main Workspace
    - |
      tb auth \
      --host $TB_HOST \
      --token $ADMIN_TOKEN

    # List changes with main Workspace
    - tb diff --no-verbose

    # Push changes to the main Workspace
    - |
      PUSH_FILE=./deployment/${CI_COMMIT_REF_NAME}-push.sh
      if [ -f "$PUSH_FILE" ]; then
        ./deployment/${CI_COMMIT_REF_NAME}-push.sh
      else
        tb push --push-deps --only-changes --force --populate --wait
      fi

    # List changes with main Workspace (should be empty)
    - tb diff
