name: Tinybird CD with versioning

on:
  workflow_call:
    inputs:
      tb_deploy:
        description: "use tb deploy based on git releases"
        required: false
        type: boolean
        default: false
    secrets:
      admin_token:
        required: true
      tb_host:
        required: true

jobs:
  push_changes:
    runs-on: ubuntu-latest
    name: Push changes to Workspace
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Set environment variables
        run: |
          GIT_BRANCH=${GITHUB_HEAD_REF}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
      - name: Install Tinybird CLI
        run: pip install tinybird-cli
      - name: Tinybird version
        run: tb --version
      - name: Check all the data files syntax
        run: tb check
      - name: Authenticate
        run: |
          tb auth \
          --host ${{ secrets.tb_host }} \
          --token ${{ secrets.admin_token }} \
      - name: List changes with Workspace
        run: tb diff --no-verbose
      - name: Push changes to Workspace
        run: |
            PUSH_FILE=./deployment/${{env.GIT_BRANCH}}-push.sh
            if [ -f "$PUSH_FILE" ]; then
              ./deployment/${{env.GIT_BRANCH}}-push.sh
            else
              if ${{ inputs.tb_deploy}}; then
                tb deploy --populate --fixtures --wait
              else
                tb push --push-deps --only-changes --fixtures --force --populate --wait
              fi
            fi
      - name: List changes with Workspace (should be empty)
        run: tb diff